FROM navikt/nginx-oidc:latest as base

ENV APP_DIR="/app" \
	APP_PATH_PREFIX="/dp-inntekt-innsyn-ui" \
	APP_CALLBACK_PATH="/dp-inntekt-innsyn-ui/oidc/callback"

COPY build /app/dp-inntekt-innsyn-ui/

COPY nais/proxy.nginx      /nginx/proxy.nginx
EXPOSE 3000 443

#multi-stage so we dont need to fetch nginx all the time
FROM base as npm
RUN apk add --update nodejs npm

FROM npm as finally

COPY package*.json ./

RUN mkdir client
WORKDIR client
COPY ./ client

RUN npm install
RUN npm build
RUN npm start