apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-innsyn-ui
spec:
  ingresses:
    - "https://dp-inntekt-innsyn-ui.nais.oera-q.local/"
    - "https://www-q0.nav.no/arbeid/dagpenger/kalkulator"
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  env:
    - name: REACT_APP_API_URL
      value: https://www-q0.nav.no/arbeid/dagpenger/kalkulator-api/
    - name: REACT_APP_AMPLITUDE_KEY
      value: 24eb6d83cfc9883c04c4eaec61251bf4

